services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=document-util'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '13000:5432'
